package adminrpc

import (
	"context"
	"crypto/sha256"
	"encoding/hex"
	"errors"
	"fmt"
	"net/url"
	"sort"
	"strconv"
	"strings"
	"time"

	"connectrpc.com/connect"
	"google.golang.org/protobuf/types/known/timestamppb"

	adminv1 "github.com/aloisdeniel/moth/gen/moth/admin/v1"
	"github.com/aloisdeniel/moth/gen/moth/admin/v1/adminv1connect"
	"github.com/aloisdeniel/moth/internal/billing"
	"github.com/aloisdeniel/moth/internal/keys"
	"github.com/aloisdeniel/moth/internal/setup"
	"github.com/aloisdeniel/moth/internal/store"
)

// MonetizationHandler implements moth.admin.v1.MonetizationService: it reads a
// project's catalog + offering, reports store-connection/drift status, and
// reconciles the catalog into App Store Connect / Google Play.
//
// Honest automation (plan/12): the App Store Connect *catalog* API key is
// write-only and never persisted server-side (moth stores only the App Store
// Server API IAP key, for the milestone-11 engine), so the admin cannot itself
// create Apple subscriptions — SyncStoreCatalog computes the plan/diff and emits
// the exact guided steps (including the `moth setup billing` command, which
// holds the ASC key in-process). Google's service account IS stored, so its
// catalog push can run server-side through the injected syncer. Every live store
// call sits behind the storeSyncer interface, nil for local/guided-only mode, so
// the handler is testable with no network.
type MonetizationHandler struct {
	store   Store
	master  keys.MasterKey
	audit   *Auditor
	now     func() time.Time
	baseURL string
	syncer  storeSyncer
}

var _ adminv1connect.MonetizationServiceHandler = (*MonetizationHandler)(nil)

// storeSyncer pushes moth's desired catalog into one live store. Injected so the
// server can wire the real store-API clients while tests substitute a no-network
// double; nil keeps the handler in local/guided-only mode.
type storeSyncer interface {
	Sync(ctx context.Context, storeName, slug, baseURL string, creds store.BillingCredentials, cat setup.DesiredCatalog) (*setup.SyncResult, error)
}

// NewMonetizationHandler builds the monetization service. syncer may be nil
// (local/guided-only reconciliation); now defaults to time.Now.
func NewMonetizationHandler(st Store, master keys.MasterKey, baseURL string, auditor *Auditor, syncer storeSyncer, now func() time.Time) *MonetizationHandler {
	if now == nil {
		now = time.Now
	}
	return &MonetizationHandler{store: st, master: master, audit: auditor, now: now, baseURL: baseURL, syncer: syncer}
}

func (h *MonetizationHandler) requireProject(ctx context.Context, projectID string) (store.Project, error) {
	p, err := h.store.GetProject(ctx, projectID)
	if err != nil {
		if errors.Is(err, store.ErrNotFound) {
			return store.Project{}, connect.NewError(connect.CodeNotFound, errors.New("project not found"))
		}
		return store.Project{}, connect.NewError(connect.CodeInternal, err)
	}
	return p, nil
}

// storeName maps the proto Store enum to the store.* string, rejecting
// STORE_UNSPECIFIED.
func storeName(s adminv1.Store) (string, error) {
	switch s {
	case adminv1.Store_STORE_APPLE:
		return store.SubscriptionStoreApple, nil
	case adminv1.Store_STORE_GOOGLE:
		return store.SubscriptionStoreGoogle, nil
	case adminv1.Store_STORE_STRIPE:
		return store.SubscriptionStoreStripe, nil
	default:
		return "", connect.NewError(connect.CodeInvalidArgument, errors.New("store must be STORE_APPLE, STORE_GOOGLE or STORE_STRIPE"))
	}
}

// productStoreSKU returns the product's SKU for the given store ("" when
// unmapped). For Stripe the "SKU" is the recurring Price id — generated by
// provisioning, not authored (see storeProvisionsIDs).
func productStoreSKU(p store.Product, storeName string) string {
	switch storeName {
	case store.SubscriptionStoreApple:
		return p.AppleProductID
	case store.SubscriptionStoreStripe:
		return p.StripePriceID
	default:
		return p.GoogleProductID
	}
}

// storeProvisionsIDs reports whether the store generates the product ids
// itself (Stripe: Product/Price ids come back from provisioning and are
// written onto moth's product), as opposed to Apple/Google whose SKUs are
// authored in moth first. A product without a Stripe price id is therefore
// "not yet provisioned", never "unmapped".
func storeProvisionsIDs(storeName string) bool {
	return storeName == store.SubscriptionStoreStripe
}

// productSyncKey is the stable key ProductResults are matched back on: the
// authored SKU for Apple/Google, moth's identifier for Stripe (whose store ids
// may not exist yet).
func productSyncKey(p store.Product, storeName string) string {
	if storeProvisionsIDs(storeName) {
		return p.Identifier
	}
	return productStoreSKU(p, storeName)
}

// productRevision is a stable fingerprint of the product state moth would push
// to a store: its SKU, price, cadence, listing and intro offer. It is recorded
// on a successful sync (product_store_sync.revision) and recomputed by the
// status/plan surfaces to detect *moth-side* drift — a price or listing edited
// in moth after the last push — without a live store read (the honest local
// diff; a store-console edit still requires a live re-sync to observe).
func productRevision(p store.Product, storeName string) string {
	sum := sha256.Sum256([]byte(strings.Join([]string{
		productStoreSKU(p, storeName),
		p.BillingPeriod,
		p.Currency,
		strconv.FormatInt(p.PriceAmountMicros, 10),
		p.DisplayName,
		p.IntroPeriod,
		strconv.FormatInt(p.IntroPriceAmountMicros, 10),
	}, "\x00")))
	return hex.EncodeToString(sum[:12])
}

// --- Offering -------------------------------------------------------------

// offeringTag normalizes an offering id: empty selects the default offering.
func offeringTag(id string) string {
	if id == "" {
		return store.DefaultOffering
	}
	return id
}

// productOffering returns the offering a product belongs to (empty tag == the
// default offering).
func productOffering(p store.Product) string {
	if p.Offering == "" {
		return store.DefaultOffering
	}
	return p.Offering
}

func (h *MonetizationHandler) GetOffering(ctx context.Context, req *connect.Request[adminv1.GetOfferingRequest]) (*connect.Response[adminv1.GetOfferingResponse], error) {
	if _, err := h.requireProject(ctx, req.Msg.ProjectId); err != nil {
		return nil, err
	}
	off, err := h.buildOffering(ctx, req.Msg.ProjectId, offeringTag(req.Msg.Offering))
	if err != nil {
		return nil, err
	}
	return connect.NewResponse(&adminv1.GetOfferingResponse{Offering: off}), nil
}

func (h *MonetizationHandler) buildOffering(ctx context.Context, projectID, tag string) (*adminv1.Offering, error) {
	products, err := h.store.ListProducts(ctx, projectID)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	var members []store.Product
	for _, p := range products {
		if productOffering(p) == tag {
			members = append(members, p)
		}
	}
	sort.SliceStable(members, func(i, j int) bool {
		if members[i].SortOrder != members[j].SortOrder {
			return members[i].SortOrder < members[j].SortOrder
		}
		return members[i].CreatedAt.Before(members[j].CreatedAt)
	})
	off := &adminv1.Offering{Identifier: tag, IsDefault: tag == store.DefaultOffering}
	for _, p := range members {
		off.ProductIds = append(off.ProductIds, p.ID)
		off.Products = append(off.Products, productProto(p))
	}
	return off, nil
}

func (h *MonetizationHandler) ReorderOffering(ctx context.Context, req *connect.Request[adminv1.ReorderOfferingRequest]) (*connect.Response[adminv1.ReorderOfferingResponse], error) {
	if _, err := h.requireProject(ctx, req.Msg.ProjectId); err != nil {
		return nil, err
	}
	tag := offeringTag(req.Msg.Offering)
	products, err := h.store.ListProducts(ctx, req.Msg.ProjectId)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	// The offering's current membership must equal the requested set exactly:
	// every current member appears once, and no stranger is included.
	current := map[string]bool{}
	for _, p := range products {
		if productOffering(p) == tag {
			current[p.ID] = true
		}
	}
	seen := map[string]bool{}
	orders := map[string]int{}
	for i, id := range req.Msg.ProductIds {
		if !current[id] {
			return nil, connect.NewError(connect.CodeInvalidArgument,
				fmt.Errorf("product %q is not in offering %q", id, tag))
		}
		if seen[id] {
			return nil, connect.NewError(connect.CodeInvalidArgument,
				fmt.Errorf("product %q listed more than once", id))
		}
		seen[id] = true
		orders[id] = i
	}
	if len(seen) != len(current) {
		return nil, connect.NewError(connect.CodeInvalidArgument,
			errors.New("every product currently in the offering must appear exactly once"))
	}
	if err := h.store.SetProductSortOrders(ctx, req.Msg.ProjectId, orders); err != nil {
		return nil, billingErr(err)
	}
	h.audit.record(ctx, entry{Action: ActionOfferingReorder, TargetType: "project", TargetID: req.Msg.ProjectId,
		ProjectID: req.Msg.ProjectId, Summary: fmt.Sprintf("Reordered offering %q (%d products)", tag, len(orders))})
	off, err := h.buildOffering(ctx, req.Msg.ProjectId, tag)
	if err != nil {
		return nil, err
	}
	return connect.NewResponse(&adminv1.ReorderOfferingResponse{Offering: off}), nil
}

// --- Status ---------------------------------------------------------------

// GetStoreCatalogStatus reports each store's credential/notification wiring and a
// per-product sync state. It computes a *live moth-side diff*: a product recorded
// in_sync whose price/period/listing has since changed in moth is reported DRIFT
// (recomputed from productRevision), not stale parity — so an edit that has not
// been re-pushed is visible immediately. Drift introduced outside moth (a price
// edited directly in Play Console / App Store Connect) is not observable from a
// persisted row; it surfaces on the next live push — for Google via the admin
// "Sync store catalog" action (which re-reads the store), for Apple via
// `moth setup billing` / `moth doctor` (moth never holds the ASC catalog key
// server-side, the honest boundary from the capability spike).
func (h *MonetizationHandler) GetStoreCatalogStatus(ctx context.Context, req *connect.Request[adminv1.GetStoreCatalogStatusRequest]) (*connect.Response[adminv1.GetStoreCatalogStatusResponse], error) {
	if _, err := h.requireProject(ctx, req.Msg.ProjectId); err != nil {
		return nil, err
	}
	creds, err := h.billingCredentials(ctx, req.Msg.ProjectId)
	if err != nil {
		return nil, err
	}
	products, err := h.store.ListProducts(ctx, req.Msg.ProjectId)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	syncs, err := h.store.ListProductStoreSyncs(ctx, req.Msg.ProjectId, "")
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}
	byKey := map[string]store.ProductStoreSync{}
	for _, s := range syncs {
		byKey[s.ProductID+"|"+s.Store] = s
	}
	resp := &adminv1.GetStoreCatalogStatusResponse{}
	for _, sn := range []string{store.SubscriptionStoreApple, store.SubscriptionStoreGoogle, store.SubscriptionStoreStripe} {
		resp.Stores = append(resp.Stores, storeStatus(sn, creds, products, byKey))
	}
	return connect.NewResponse(resp), nil
}

func storeStatus(sn string, creds store.BillingCredentials, products []store.Product, byKey map[string]store.ProductStoreSync) *adminv1.StoreCatalogStatus {
	st := &adminv1.StoreCatalogStatus{
		Store:              adminStoreProto(sn),
		CredentialsPresent: credentialsPresent(sn, creds),
		NotificationsWired: notificationsWired(sn, creds),
	}
	var latest *time.Time
	for _, p := range products {
		st.ProductsTotal++
		sku := productStoreSKU(p, sn)
		if sku == "" && !storeProvisionsIDs(sn) {
			// Apple/Google SKUs are authored in moth: no SKU means the operator
			// has not mapped the tier onto the store. Stripe ids are generated
			// by provisioning, so an id-less product is PENDING, not unmapped.
			st.ProductsUnmapped++
			continue
		}
		state := &adminv1.ProductSyncState{
			ProductId:      p.ID,
			Identifier:     p.Identifier,
			StoreProductId: sku,
			Status:         adminv1.ProductSyncStatus_PRODUCT_SYNC_STATUS_PENDING,
		}
		if s, ok := byKey[p.ID+"|"+sn]; ok {
			state.Revision = s.Revision
			state.Error = s.Error
			if s.SyncedAt != nil {
				state.LastSyncTime = timestamppb.New(*s.SyncedAt)
				if latest == nil || s.SyncedAt.After(*latest) {
					latest = s.SyncedAt
				}
			}
			// Live moth-side diff: a row recorded in_sync whose product has since
			// changed in moth (price/listing/period edit) is drift, not parity.
			effective := s.Status
			if s.Status == store.ProductSyncInSync && s.Revision != "" && s.Revision != productRevision(p, sn) {
				effective = store.ProductSyncDrift
			}
			state.Status = syncStatusProto(effective)
			switch effective {
			case store.ProductSyncInSync:
				st.ProductsInSync++
			case store.ProductSyncDrift:
				st.ProductsDrift++
			case store.ProductSyncError:
				st.ProductsError++
			}
		}
		st.Products = append(st.Products, state)
	}
	if latest != nil {
		st.LastSyncTime = timestamppb.New(*latest)
	}
	return st
}

func credentialsPresent(sn string, c store.BillingCredentials) bool {
	switch sn {
	case store.SubscriptionStoreApple:
		return len(c.AppleIAPKeyEnc) > 0 && c.AppleBundleID != ""
	case store.SubscriptionStoreStripe:
		return len(c.StripeSecretKeyEnc) > 0
	default:
		return len(c.GoogleServiceAccountEnc) > 0 && c.GooglePackageName != ""
	}
}

func notificationsWired(sn string, c store.BillingCredentials) bool {
	switch sn {
	case store.SubscriptionStoreApple:
		return len(c.AppleNotificationSecretEnc) > 0
	case store.SubscriptionStoreStripe:
		return len(c.StripeWebhookSecretEnc) > 0
	default:
		return c.GooglePubsubTopic != ""
	}
}

// --- Sync -----------------------------------------------------------------

func (h *MonetizationHandler) SyncStoreCatalog(ctx context.Context, req *connect.Request[adminv1.SyncStoreCatalogRequest]) (*connect.Response[adminv1.SyncStoreCatalogResponse], error) {
	project, err := h.requireProject(ctx, req.Msg.ProjectId)
	if err != nil {
		return nil, err
	}
	sn, err := storeName(req.Msg.Store)
	if err != nil {
		return nil, err
	}
	creds, err := h.billingCredentials(ctx, req.Msg.ProjectId)
	if err != nil {
		return nil, err
	}
	products, err := h.store.ListProducts(ctx, req.Msg.ProjectId)
	if err != nil {
		return nil, connect.NewError(connect.CodeInternal, err)
	}

	// Live apply: push through the injected syncer when credentials are present
	// and a syncer is wired, then persist the per-store sync rows + store-id
	// write-back. Otherwise fall back to the local plan + guided steps.
	if !req.Msg.DryRun && h.syncer != nil && credentialsPresent(sn, creds) {
		resp, applyErr := h.applySync(ctx, project, sn, creds, products)
		if applyErr == nil {
			return connect.NewResponse(resp), nil
		}
		// Surface the failure but still return the honest plan below rather than
		// a bare 500, so the operator sees what would change.
		return connect.NewResponse(h.planResponse(ctx, project, sn, creds, products, applyErr.Error())), nil
	}
	return connect.NewResponse(h.planResponse(ctx, project, sn, creds, products, "")), nil
}

// planResponse computes the honest local plan (moth's catalog vs the last-known
// product_store_sync state) plus store-level guided steps, without touching any
// live store.
func (h *MonetizationHandler) planResponse(ctx context.Context, project store.Project, sn string, creds store.BillingCredentials, products []store.Product, applyErr string) *adminv1.SyncStoreCatalogResponse {
	resp := &adminv1.SyncStoreCatalogResponse{Store: adminStoreProto(sn), InSync: true}
	mapped := 0
	for _, p := range products {
		sku := productStoreSKU(p, sn)
		if sku == "" && !storeProvisionsIDs(sn) {
			continue
		}
		mapped++
		label := sku
		if label == "" {
			label = p.Identifier // Stripe ids are generated by the push itself
		}
		item := &adminv1.ProductSyncItem{
			ProductId:      p.ID,
			Identifier:     p.Identifier,
			StoreProductId: sku,
			Action:         adminv1.SyncAction_SYNC_ACTION_CREATE,
			Summary: fmt.Sprintf("create %s at %s %s / %s", label,
				formatMicros(p.PriceAmountMicros), p.Currency, p.BillingPeriod),
		}
		// Honest plan: a Stripe push includes every product, so one whose
		// billing period cannot map to a Stripe cadence WILL fail the apply —
		// say so up front instead of implying a clean sync.
		if sn == store.SubscriptionStoreStripe {
			if _, _, err := billing.StripeRecurringForPeriod(p.BillingPeriod); err != nil {
				item.Error = err.Error()
				item.Summary = fmt.Sprintf("%s cannot sync: %s", label, err.Error())
			}
		}
		sync, err := h.store.GetProductStoreSync(ctx, p.ID, sn)
		if err == nil {
			// Recompute moth's desired fingerprint: a recorded in_sync row whose
			// product has since changed in moth is drift needing an UPDATE, not a
			// NOOP — the honest local diff the status panel surfaces.
			drifted := sync.Revision != "" && sync.Revision != productRevision(p, sn)
			switch {
			case sync.Status == store.ProductSyncInSync && !drifted:
				item.Action = adminv1.SyncAction_SYNC_ACTION_NOOP
				item.Summary = fmt.Sprintf("%s already in sync", label)
			default:
				item.Action = adminv1.SyncAction_SYNC_ACTION_UPDATE
				item.Summary = fmt.Sprintf("update %s to %s %s / %s", label,
					formatMicros(p.PriceAmountMicros), p.Currency, p.BillingPeriod)
				if sn == store.SubscriptionStoreStripe {
					// Stripe prices are immutable: the push creates a NEW Price
					// and re-points the tier; existing subscribers keep theirs.
					item.Summary += " (a new Stripe Price will be created; existing subscribers keep the old price)"
				}
			}
		}
		if item.Action != adminv1.SyncAction_SYNC_ACTION_NOOP {
			resp.InSync = false
		}
		resp.Items = append(resp.Items, item)
	}
	if mapped == 0 {
		resp.InSync = false
	}
	resp.GuidedSteps = guidedSteps(sn, project.Slug, h.baseURL, creds, mapped, applyErr, h.rtdnToken(creds))
	return resp
}

// rtdnToken decrypts the project's stored RTDN shared secret, or "" when none is
// stored / decryption fails. The token is appended to the RTDN endpoint moth
// hands out so an operator wiring the Play push subscription by hand configures a
// URL the receiver actually authenticates (handleGoogleRTDN).
func (h *MonetizationHandler) rtdnToken(creds store.BillingCredentials) string {
	if len(creds.GoogleRTDNSecretEnc) == 0 {
		return ""
	}
	secret, err := h.master.Decrypt(creds.GoogleRTDNSecretEnc)
	if err != nil {
		return ""
	}
	return string(secret)
}

// applySync pushes the catalog through the injected syncer and persists the
// results (per-store sync rows + the store-id write-back: Stripe's generated
// Price/Product ids land back on moth's product).
func (h *MonetizationHandler) applySync(ctx context.Context, project store.Project, sn string, creds store.BillingCredentials, products []store.Product) (*adminv1.SyncStoreCatalogResponse, error) {
	cat := setup.DesiredCatalogFromProducts(productsProto(products), project.Slug, sn)
	res, err := h.syncer.Sync(ctx, sn, project.Slug, h.baseURL, creds, cat)
	if err != nil {
		return nil, err
	}
	// Index products by their sync key (SKU, or moth identifier for Stripe) to
	// map results back to moth ids.
	byKey := map[string]store.Product{}
	for _, p := range products {
		if key := productSyncKey(p, sn); key != "" {
			byKey[key] = p
		}
	}
	now := h.now()
	resp := &adminv1.SyncStoreCatalogResponse{Store: adminStoreProto(sn), InSync: true}
	for _, pr := range res.Products {
		p, ok := byKey[pr.ProductID]
		if !ok {
			continue
		}
		// Stripe id write-back: provisioning generated (or re-pointed) the
		// Price/Product ids; record them on the moth product before computing
		// the revision so the status surfaces see parity, not synthetic drift.
		// A failed tier can still carry a created Product id (price-stage
		// failure): record it too, so a re-run reuses the Product instead of
		// provisioning a duplicate.
		if sn == store.SubscriptionStoreStripe {
			changed := false
			if pr.StoreID != "" && p.StripePriceID != pr.StoreID {
				p.StripePriceID = pr.StoreID
				changed = true
			}
			if pr.StoreParentID != "" && p.StripeProductID != pr.StoreParentID {
				p.StripeProductID = pr.StoreParentID
				changed = true
			}
			if changed {
				p.UpdatedAt = now
				if err := h.store.UpdateProduct(ctx, p); err != nil {
					return nil, err
				}
			}
		}
		storeProductID := pr.ProductID
		if storeProvisionsIDs(sn) {
			storeProductID = pr.StoreID
		}
		item := &adminv1.ProductSyncItem{
			ProductId:      p.ID,
			Identifier:     p.Identifier,
			StoreProductId: storeProductID,
			Summary:        pr.Detail,
		}
		status := store.ProductSyncInSync
		switch pr.Action {
		case setup.ActionCreated:
			item.Action = adminv1.SyncAction_SYNC_ACTION_CREATE
			resp.InSync = false
		case setup.ActionUpdated:
			item.Action = adminv1.SyncAction_SYNC_ACTION_UPDATE
			resp.InSync = false
		case setup.ActionUnchanged:
			item.Action = adminv1.SyncAction_SYNC_ACTION_NOOP
		case setup.ActionManual:
			item.Action = adminv1.SyncAction_SYNC_ACTION_GUIDED
		case setup.ActionFailed:
			item.Action = adminv1.SyncAction_SYNC_ACTION_GUIDED
			item.Error = pr.Detail
			status = store.ProductSyncError
			resp.InSync = false
		}
		item.Status = syncStatusProto(status)
		row := store.ProductStoreSync{
			ProductID: p.ID, Store: sn, Status: status,
			StoreProductID: storeProductID, Revision: productRevision(p, sn), Error: item.Error,
			SyncedAt: &now, CreatedAt: now, UpdatedAt: now,
		}
		if err := h.store.UpsertProductStoreSync(ctx, row); err != nil {
			return nil, err
		}
		resp.Items = append(resp.Items, item)
	}
	for _, m := range res.ManualSteps {
		resp.GuidedSteps = append(resp.GuidedSteps, manualStepProto(m))
	}
	for _, n := range res.Notifications {
		if n.Action == setup.ActionManual {
			resp.GuidedSteps = append(resp.GuidedSteps, &adminv1.GuidedStep{
				Title: "Wire notification: " + n.Kind, Detail: n.Detail,
				Values: []*adminv1.GuidedValue{{Label: "endpoint", Value: n.Endpoint}},
			})
		}
	}
	// Stripe webhook wiring stays CLI-only from the admin path: the signing
	// secret is revealed by Stripe exactly once at creation, and `moth setup
	// billing` creates the endpoint and persists the secret in the same breath.
	// When moth holds no webhook secret yet, say so honestly rather than leave
	// deliveries to fail unverified.
	if sn == store.SubscriptionStoreStripe && len(creds.StripeWebhookSecretEnc) == 0 {
		resp.GuidedSteps = append(resp.GuidedSteps, stripeWebhookGuidedStep(project.Slug, h.baseURL))
	}
	// Honest reporting: if the syncer confirmed no products (the Apple guided-only
	// path — moth never holds the ASC catalog key, so it returns only ManualSteps),
	// the catalog was not actually pushed or verified. Reporting InSync here would
	// falsely claim parity; a project with mapped products but zero confirmations
	// is not in sync (mirrors planResponse, which reports CREATE/InSync=false for
	// the same state).
	if len(resp.Items) == 0 {
		resp.InSync = false
	}
	h.audit.record(ctx, entry{Action: ActionStoreCatalogSync, TargetType: "project", TargetID: project.ID,
		ProjectID: project.ID, Summary: fmt.Sprintf("Synced %s catalog (%d products)", sn, len(resp.Items))})
	return resp, nil
}

// --- helpers --------------------------------------------------------------

func (h *MonetizationHandler) billingCredentials(ctx context.Context, projectID string) (store.BillingCredentials, error) {
	creds, err := h.store.GetBillingCredentials(ctx, projectID)
	if errors.Is(err, store.ErrNotFound) {
		return store.BillingCredentials{}, nil
	}
	if err != nil {
		return store.BillingCredentials{}, connect.NewError(connect.CodeInternal, err)
	}
	return creds, nil
}

func productsProto(products []store.Product) []*adminv1.Product {
	out := make([]*adminv1.Product, 0, len(products))
	for _, p := range products {
		out = append(out, productProto(p))
	}
	return out
}

func syncStatusProto(s string) adminv1.ProductSyncStatus {
	switch s {
	case store.ProductSyncInSync:
		return adminv1.ProductSyncStatus_PRODUCT_SYNC_STATUS_IN_SYNC
	case store.ProductSyncDrift:
		return adminv1.ProductSyncStatus_PRODUCT_SYNC_STATUS_DRIFT
	case store.ProductSyncError:
		return adminv1.ProductSyncStatus_PRODUCT_SYNC_STATUS_ERROR
	default:
		return adminv1.ProductSyncStatus_PRODUCT_SYNC_STATUS_PENDING
	}
}

func manualStepProto(m setup.ManualStep) *adminv1.GuidedStep {
	g := &adminv1.GuidedStep{Title: m.Title, Detail: m.Reason, Url: m.URL}
	for i, ins := range m.Instructions {
		g.Values = append(g.Values, &adminv1.GuidedValue{Label: fmt.Sprintf("step %d", i+1), Value: ins})
	}
	return g
}

func formatMicros(micros int64) string {
	return fmt.Sprintf("%.2f", float64(micros)/1_000_000)
}

// stripeWebhookGuidedStep is the honest "no webhook secret stored" step: the
// signing secret is revealed by Stripe exactly once at endpoint creation, so
// the admin cannot wire it after the fact — `moth setup billing` creates the
// endpoint and persists the secret in the same run, or the operator registers
// it in the Stripe dashboard and pastes the secret into store credentials.
func stripeWebhookGuidedStep(slug, baseURL string) *adminv1.GuidedStep {
	endpoint := strings.TrimSuffix(baseURL, "/") + "/billing/stripe/webhook/" + slug
	return &adminv1.GuidedStep{
		Title:  "Wire the Stripe webhook",
		Detail: "moth holds no Stripe webhook signing secret, so subscription events cannot be verified. Run `moth setup billing` to create the endpoint via the API and store the secret, or register it in the Stripe dashboard and paste the signing secret into store credentials.",
		Url:    "https://dashboard.stripe.com/webhooks",
		Values: []*adminv1.GuidedValue{
			{Label: "command", Value: "moth setup billing --project " + slug + " --stripe-secret-key <key>"},
			{Label: "endpoint URL", Value: endpoint},
			{Label: "events", Value: strings.Join(setup.StripeWebhookEvents, ", ")},
		},
	}
}

// guidedSteps returns the store-level manual steps the catalog APIs cannot
// perform, with the exact values to paste (honest automation — never silently
// skipped). These accompany the local plan when no live push runs.
func guidedSteps(sn, slug, baseURL string, creds store.BillingCredentials, mapped int, applyErr, rtdnToken string) []*adminv1.GuidedStep {
	var steps []*adminv1.GuidedStep
	if applyErr != "" {
		steps = append(steps, &adminv1.GuidedStep{
			Title:  "Store push reported an error",
			Detail: applyErr,
		})
	}
	base := strings.TrimSuffix(baseURL, "/")
	if sn == store.SubscriptionStoreApple {
		if !credentialsPresent(sn, creds) {
			steps = append(steps, &adminv1.GuidedStep{
				Title:  "Configure Apple billing credentials",
				Detail: "Add the App Store Server API In-App-Purchase key and bundle id (Monetization → store credentials) before pushing.",
			})
		}
		steps = append(steps, &adminv1.GuidedStep{
			Title:  "Push the Apple catalog with the CLI",
			Detail: "The App Store Connect catalog API key is never stored by moth. Run `moth setup billing` with the ASC key to create/update the subscriptions, then submit the new subscriptions for review in App Store Connect (no API).",
			Values: []*adminv1.GuidedValue{{Label: "command", Value: "moth setup billing --project " + slug + " --asc-p8 <path> --asc-key-id <id> --asc-issuer-id <id> --apple-app-id <id>"}},
		})
		steps = append(steps, &adminv1.GuidedStep{
			Title:  "Register the App Store Server Notification URL",
			Detail: "In App Store Connect → App Information → App Store Server Notifications (V2), set the Production and Sandbox URL to moth's endpoint.",
			Url:    "https://appstoreconnect.apple.com",
			Values: []*adminv1.GuidedValue{{Label: "notification URL", Value: base + "/billing/apple/notifications/" + slug}},
		})
		return steps
	}
	if sn == store.SubscriptionStoreStripe {
		if !credentialsPresent(sn, creds) {
			steps = append(steps, &adminv1.GuidedStep{
				Title:  "Configure Stripe billing credentials",
				Detail: "Add the Stripe restricted secret key (Monetization → store credentials) before pushing; the same key drives catalog provisioning and runtime.",
			})
		}
		if len(creds.StripeWebhookSecretEnc) == 0 {
			steps = append(steps, stripeWebhookGuidedStep(slug, baseURL))
		}
		return steps
	}
	if !credentialsPresent(sn, creds) {
		steps = append(steps, &adminv1.GuidedStep{
			Title:  "Configure Google billing credentials",
			Detail: "Add the Play Developer service-account JSON and package name (Monetization → store credentials) before pushing.",
		})
	}
	steps = append(steps, &adminv1.GuidedStep{
		Title:  "Confirm Play Console availability & pricing matrix",
		Detail: "The Android Publisher API provisions the base plan + base price; activate the subscription and set country availability in Play Console.",
		Url:    "https://play.google.com/console",
	})
	rtdnEndpoint := base + "/billing/google/rtdn/" + slug
	if rtdnToken != "" {
		rtdnEndpoint += "?token=" + url.QueryEscape(rtdnToken)
	}
	steps = append(steps, &adminv1.GuidedStep{
		Title:  "Point Play RTDN at moth's endpoint",
		Detail: "In Play Console → Monetization setup → Real-time developer notifications, set the topic and confirm the push subscription targets moth (the endpoint carries the shared-secret token the webhook authenticates).",
		Values: []*adminv1.GuidedValue{
			{Label: "RTDN endpoint", Value: rtdnEndpoint},
			{Label: "topic", Value: creds.GooglePubsubTopic},
		},
	})
	return steps
}
