package adminrpc

import (
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"net/http/httptest"
	"strconv"
	"strings"
	"sync"
	"testing"
	"time"

	"connectrpc.com/connect"

	adminv1 "github.com/aloisdeniel/moth/gen/moth/admin/v1"
	"github.com/aloisdeniel/moth/internal/setup"
	"github.com/aloisdeniel/moth/internal/store"
)

func TestSyncStoreCatalogStripeDryRunPlan(t *testing.T) {
	h, st, _, project := newMonetizationTestHandler(t, nil)
	ctx := context.Background()
	makeProduct(t, st, project.ID, "monthly", "", 0, "") // no store ids at all

	resp, err := h.SyncStoreCatalog(ctx, connect.NewRequest(&adminv1.SyncStoreCatalogRequest{
		ProjectId: project.ID, Store: adminv1.Store_STORE_STRIPE, DryRun: true}))
	if err != nil {
		t.Fatalf("dry-run must not error: %v", err)
	}
	// Stripe ids are generated by provisioning: an id-less product is a CREATE
	// in the plan, never invisible/unmapped.
	if len(resp.Msg.Items) != 1 || resp.Msg.Items[0].Action != adminv1.SyncAction_SYNC_ACTION_CREATE {
		t.Fatalf("expected one CREATE item, got %+v", resp.Msg.Items)
	}
	if resp.Msg.InSync {
		t.Fatal("plan with a pending create must not be in sync")
	}
	var titles []string
	for _, g := range resp.Msg.GuidedSteps {
		titles = append(titles, g.Title)
	}
	joined := strings.Join(titles, "|")
	if !strings.Contains(joined, "Configure Stripe billing credentials") ||
		!strings.Contains(joined, "Wire the Stripe webhook") {
		t.Fatalf("guided steps = %v", titles)
	}
}

func TestSyncStoreCatalogStripeApplyWritesBackIDs(t *testing.T) {
	syncer := &fakeSyncer{result: &setup.SyncResult{
		Store: store.SubscriptionStoreStripe,
		Products: []setup.ProductResult{{
			ProductID: "monthly", StoreID: "price_1", StoreParentID: "prod_1",
			Action: setup.ActionCreated, Detail: "created Stripe product prod_1 with recurring price price_1",
		}},
	}}
	h, st, master, project := newMonetizationTestHandler(t, syncer)
	ctx := context.Background()
	p := makeProduct(t, st, project.ID, "monthly", "", 0, "")

	keyEnc, err := master.Encrypt([]byte("sk_test_abc"))
	if err != nil {
		t.Fatal(err)
	}
	if err := st.UpsertBillingCredentials(ctx, store.BillingCredentials{
		ProjectID: project.ID, StripeSecretKeyEnc: keyEnc,
		CreatedAt: time.Now(), UpdatedAt: time.Now(),
	}); err != nil {
		t.Fatal(err)
	}

	resp, err := h.SyncStoreCatalog(ctx, connect.NewRequest(&adminv1.SyncStoreCatalogRequest{
		ProjectId: project.ID, Store: adminv1.Store_STORE_STRIPE, DryRun: false}))
	if err != nil {
		t.Fatal(err)
	}
	if !syncer.called {
		t.Fatal("expected the live syncer to run with Stripe creds present")
	}
	if len(resp.Msg.Items) != 1 || resp.Msg.Items[0].Action != adminv1.SyncAction_SYNC_ACTION_CREATE ||
		resp.Msg.Items[0].StoreProductId != "price_1" {
		t.Fatalf("items = %+v", resp.Msg.Items)
	}

	// The generated ids landed back on the moth product.
	stored, err := st.GetProduct(ctx, project.ID, p.ID)
	if err != nil {
		t.Fatal(err)
	}
	if stored.StripePriceID != "price_1" || stored.StripeProductID != "prod_1" {
		t.Fatalf("write-back missing: %+v", stored)
	}

	// The product_store_sync row records the price id + post-write-back
	// revision, so the status surface reports parity (not synthetic drift).
	row, err := st.GetProductStoreSync(ctx, p.ID, store.SubscriptionStoreStripe)
	if err != nil {
		t.Fatal(err)
	}
	if row.Status != store.ProductSyncInSync || row.StoreProductID != "price_1" {
		t.Fatalf("sync row = %+v", row)
	}
	if row.Revision != productRevision(stored, store.SubscriptionStoreStripe) {
		t.Fatal("revision was computed before the id write-back")
	}
	stat, err := h.GetStoreCatalogStatus(ctx, connect.NewRequest(&adminv1.GetStoreCatalogStatusRequest{ProjectId: project.ID}))
	if err != nil {
		t.Fatal(err)
	}
	var stripe *adminv1.StoreCatalogStatus
	for _, s := range stat.Msg.Stores {
		if s.Store == adminv1.Store_STORE_STRIPE {
			stripe = s
		}
	}
	if stripe == nil || stripe.ProductsInSync != 1 || stripe.ProductsUnmapped != 0 {
		t.Fatalf("stripe status = %+v", stripe)
	}
	if !stripe.CredentialsPresent || stripe.NotificationsWired {
		t.Fatalf("expected creds present, notifications unwired: %+v", stripe)
	}

	// No webhook secret stored yet: the apply surfaces the guided step (the
	// CLI is the path that can persist the secret — Stripe reveals it once).
	var guided []string
	for _, g := range resp.Msg.GuidedSteps {
		guided = append(guided, g.Title)
	}
	if !strings.Contains(strings.Join(guided, "|"), "Wire the Stripe webhook") {
		t.Fatalf("guided steps = %v", guided)
	}

	// A later price edit plans an UPDATE that names Stripe's new-Price
	// semantics — the plan's honesty requirement.
	stored.PriceAmountMicros = 4_990_000
	if err := st.UpdateProduct(ctx, stored); err != nil {
		t.Fatal(err)
	}
	plan, err := h.SyncStoreCatalog(ctx, connect.NewRequest(&adminv1.SyncStoreCatalogRequest{
		ProjectId: project.ID, Store: adminv1.Store_STORE_STRIPE, DryRun: true}))
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.Msg.Items) != 1 || plan.Msg.Items[0].Action != adminv1.SyncAction_SYNC_ACTION_UPDATE {
		t.Fatalf("plan items = %+v", plan.Msg.Items)
	}
	if !strings.Contains(plan.Msg.Items[0].Summary, "new Stripe Price") {
		t.Fatalf("update summary hides price immutability: %q", plan.Msg.Items[0].Summary)
	}
}

// TestSyncStoreCatalogStripeUnmappablePeriod: a product whose billing period
// cannot map onto a Stripe cadence must fail honestly end to end — the apply
// records an error row (never silently omits the product while claiming
// parity), and the dry-run plan announces the failure up front.
func TestSyncStoreCatalogStripeUnmappablePeriod(t *testing.T) {
	d := newAdminStripeDouble(t)
	_, st, master, project := newBillingTestHandler(t)
	now := time.Date(2026, 7, 16, 12, 0, 0, 0, time.UTC)
	syncer := LiveStoreSyncer{master: master, httpc: http.DefaultClient, stripeBaseURL: d.srv.URL}
	h := NewMonetizationHandler(st, master, "https://moth.example", nil, syncer, func() time.Time { return now })
	ctx := context.Background()
	p := makeProduct(t, st, project.ID, "typo", "", 0, "")
	p.BillingPeriod = "montly" // sic — an operator typo, not a valid cadence
	if err := st.UpdateProduct(ctx, p); err != nil {
		t.Fatal(err)
	}

	keyEnc, err := master.Encrypt([]byte("sk_test_live"))
	if err != nil {
		t.Fatal(err)
	}
	if err := st.UpsertBillingCredentials(ctx, store.BillingCredentials{
		ProjectID: project.ID, StripeSecretKeyEnc: keyEnc, CreatedAt: now, UpdatedAt: now,
	}); err != nil {
		t.Fatal(err)
	}

	// The dry-run plan already says the product cannot sync.
	plan, err := h.SyncStoreCatalog(ctx, connect.NewRequest(&adminv1.SyncStoreCatalogRequest{
		ProjectId: project.ID, Store: adminv1.Store_STORE_STRIPE, DryRun: true}))
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.Msg.Items) != 1 || plan.Msg.Items[0].Error == "" ||
		!strings.Contains(plan.Msg.Items[0].Summary, "cannot sync") {
		t.Fatalf("plan hides the unmappable period: %+v", plan.Msg.Items)
	}
	if plan.Msg.InSync {
		t.Fatal("plan with an unmappable product must not claim parity")
	}

	// The apply reports the product as failed and records the error row.
	resp, err := h.SyncStoreCatalog(ctx, connect.NewRequest(&adminv1.SyncStoreCatalogRequest{
		ProjectId: project.ID, Store: adminv1.Store_STORE_STRIPE, DryRun: false}))
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Msg.Items) != 1 {
		t.Fatalf("the unmappable product vanished from the apply: %+v", resp.Msg.Items)
	}
	item := resp.Msg.Items[0]
	if item.Error == "" || !strings.Contains(item.Error, "montly") ||
		item.Status != adminv1.ProductSyncStatus_PRODUCT_SYNC_STATUS_ERROR {
		t.Fatalf("apply item = %+v, want an error naming the period", item)
	}
	if resp.Msg.InSync {
		t.Fatal("apply with a failed product must not claim the catalog is in sync")
	}
	row, err := st.GetProductStoreSync(ctx, p.ID, store.SubscriptionStoreStripe)
	if err != nil {
		t.Fatal(err)
	}
	if row.Status != store.ProductSyncError || !strings.Contains(row.Error, "montly") {
		t.Fatalf("sync row = %+v, want status error", row)
	}
	// Nothing was provisioned in Stripe for the broken product.
	if len(d.products) != 0 || len(d.prices) != 0 {
		t.Fatalf("stripe resources created for an unmappable product: %d/%d", len(d.products), len(d.prices))
	}
}

// adminStripeDouble is a minimal Stripe API double (products + prices) for the
// LiveStoreSyncer end-to-end test; the full double lives in internal/setup.
type adminStripeDouble struct {
	srv *httptest.Server

	mu       sync.Mutex
	seq      int
	prices   map[string]map[string]any
	products map[string]string // id -> name
}

func newAdminStripeDouble(t *testing.T) *adminStripeDouble {
	t.Helper()
	d := &adminStripeDouble{prices: map[string]map[string]any{}, products: map[string]string{}}
	mux := http.NewServeMux()
	mux.HandleFunc("POST /v1/products", func(w http.ResponseWriter, r *http.Request) {
		d.mu.Lock()
		defer d.mu.Unlock()
		_ = r.ParseForm()
		d.seq++
		id := fmt.Sprintf("prod_%d", d.seq)
		d.products[id] = r.PostForm.Get("name")
		_ = json.NewEncoder(w).Encode(map[string]any{"id": id, "name": d.products[id]})
	})
	mux.HandleFunc("GET /v1/products/{id}", func(w http.ResponseWriter, r *http.Request) {
		d.mu.Lock()
		defer d.mu.Unlock()
		name, ok := d.products[r.PathValue("id")]
		if !ok {
			w.WriteHeader(http.StatusNotFound)
			_, _ = w.Write([]byte(`{"error":{"message":"no such product"}}`))
			return
		}
		_ = json.NewEncoder(w).Encode(map[string]any{"id": r.PathValue("id"), "name": name})
	})
	mux.HandleFunc("POST /v1/products/{id}", func(w http.ResponseWriter, r *http.Request) {
		d.mu.Lock()
		defer d.mu.Unlock()
		_ = r.ParseForm()
		id := r.PathValue("id")
		if _, ok := d.products[id]; !ok {
			w.WriteHeader(http.StatusNotFound)
			_, _ = w.Write([]byte(`{"error":{"message":"no such product"}}`))
			return
		}
		d.products[id] = r.PostForm.Get("name")
		_ = json.NewEncoder(w).Encode(map[string]any{"id": id, "name": d.products[id]})
	})
	mux.HandleFunc("POST /v1/prices", func(w http.ResponseWriter, r *http.Request) {
		d.mu.Lock()
		defer d.mu.Unlock()
		_ = r.ParseForm()
		d.seq++
		id := fmt.Sprintf("price_%d", d.seq)
		amount, _ := strconv.ParseInt(r.PostForm.Get("unit_amount"), 10, 64)
		count, _ := strconv.Atoi(r.PostForm.Get("recurring[interval_count]"))
		if count == 0 {
			count = 1
		}
		price := map[string]any{
			"id": id, "product": r.PostForm.Get("product"), "unit_amount": amount,
			"currency": r.PostForm.Get("currency"), "active": true,
			"recurring": map[string]any{
				"interval": r.PostForm.Get("recurring[interval]"), "interval_count": count},
		}
		d.prices[id] = price
		_ = json.NewEncoder(w).Encode(price)
	})
	mux.HandleFunc("GET /v1/prices/{id}", func(w http.ResponseWriter, r *http.Request) {
		d.mu.Lock()
		defer d.mu.Unlock()
		price, ok := d.prices[r.PathValue("id")]
		if !ok {
			w.WriteHeader(http.StatusNotFound)
			_, _ = w.Write([]byte(`{"error":{"message":"no such price"}}`))
			return
		}
		_ = json.NewEncoder(w).Encode(price)
	})
	d.srv = httptest.NewServer(mux)
	t.Cleanup(d.srv.Close)
	return d
}

// TestLiveStoreSyncerStripeEndToEnd drives the real LiveStoreSyncer (decrypting
// the stored key, calling the Stripe API double) through the handler: the
// admin "create in Stripe" flow provisions Product + Price, writes the ids
// back, and a second apply reports parity.
func TestLiveStoreSyncerStripeEndToEnd(t *testing.T) {
	d := newAdminStripeDouble(t)
	_, st, master, project := newBillingTestHandler(t)
	now := time.Date(2026, 7, 16, 12, 0, 0, 0, time.UTC)
	syncer := LiveStoreSyncer{master: master, httpc: http.DefaultClient, stripeBaseURL: d.srv.URL}
	h := NewMonetizationHandler(st, master, "https://moth.example", nil, syncer, func() time.Time { return now })
	ctx := context.Background()
	p := makeProduct(t, st, project.ID, "monthly", "", 0, "")

	keyEnc, err := master.Encrypt([]byte("sk_test_live"))
	if err != nil {
		t.Fatal(err)
	}
	if err := st.UpsertBillingCredentials(ctx, store.BillingCredentials{
		ProjectID: project.ID, StripeSecretKeyEnc: keyEnc,
		CreatedAt: now, UpdatedAt: now,
	}); err != nil {
		t.Fatal(err)
	}

	resp, err := h.SyncStoreCatalog(ctx, connect.NewRequest(&adminv1.SyncStoreCatalogRequest{
		ProjectId: project.ID, Store: adminv1.Store_STORE_STRIPE, DryRun: false}))
	if err != nil {
		t.Fatal(err)
	}
	if len(resp.Msg.Items) != 1 || resp.Msg.Items[0].Action != adminv1.SyncAction_SYNC_ACTION_CREATE {
		t.Fatalf("items = %+v", resp.Msg.Items)
	}
	stored, err := st.GetProduct(ctx, project.ID, p.ID)
	if err != nil {
		t.Fatal(err)
	}
	if !strings.HasPrefix(stored.StripePriceID, "price_") || !strings.HasPrefix(stored.StripeProductID, "prod_") {
		t.Fatalf("write-back missing: %+v", stored)
	}

	// Second apply: the syncer reads the price back from the double and
	// reports parity — idempotent, nothing recreated.
	resp2, err := h.SyncStoreCatalog(ctx, connect.NewRequest(&adminv1.SyncStoreCatalogRequest{
		ProjectId: project.ID, Store: adminv1.Store_STORE_STRIPE, DryRun: false}))
	if err != nil {
		t.Fatal(err)
	}
	if len(resp2.Msg.Items) != 1 || resp2.Msg.Items[0].Action != adminv1.SyncAction_SYNC_ACTION_NOOP {
		t.Fatalf("second apply items = %+v", resp2.Msg.Items)
	}
	if !resp2.Msg.InSync {
		t.Fatal("second apply should report in sync")
	}
	if len(d.prices) != 1 {
		t.Fatalf("second apply created prices: %d", len(d.prices))
	}

	// Display-name edit in moth: the dry-run plans an UPDATE (the revision
	// fingerprints the display name) and the apply renames the Stripe Product
	// in place — no new Price for a name-only drift.
	stored.DisplayName = "Monthly Plus"
	stored.UpdatedAt = now
	if err := st.UpdateProduct(ctx, stored); err != nil {
		t.Fatal(err)
	}
	plan, err := h.SyncStoreCatalog(ctx, connect.NewRequest(&adminv1.SyncStoreCatalogRequest{
		ProjectId: project.ID, Store: adminv1.Store_STORE_STRIPE, DryRun: true}))
	if err != nil {
		t.Fatal(err)
	}
	if len(plan.Msg.Items) != 1 || plan.Msg.Items[0].Action != adminv1.SyncAction_SYNC_ACTION_UPDATE {
		t.Fatalf("rename plan items = %+v", plan.Msg.Items)
	}
	resp3, err := h.SyncStoreCatalog(ctx, connect.NewRequest(&adminv1.SyncStoreCatalogRequest{
		ProjectId: project.ID, Store: adminv1.Store_STORE_STRIPE, DryRun: false}))
	if err != nil {
		t.Fatal(err)
	}
	if len(resp3.Msg.Items) != 1 || resp3.Msg.Items[0].Action != adminv1.SyncAction_SYNC_ACTION_UPDATE ||
		!strings.Contains(resp3.Msg.Items[0].Summary, "renamed product") {
		t.Fatalf("rename apply items = %+v", resp3.Msg.Items)
	}
	if got := d.products[stored.StripeProductID]; got != "Monthly Plus" {
		t.Fatalf("stripe product name = %q, want renamed", got)
	}
	if len(d.prices) != 1 {
		t.Fatalf("rename apply created prices: %d", len(d.prices))
	}

	// Fourth apply: the rename converged.
	resp4, err := h.SyncStoreCatalog(ctx, connect.NewRequest(&adminv1.SyncStoreCatalogRequest{
		ProjectId: project.ID, Store: adminv1.Store_STORE_STRIPE, DryRun: false}))
	if err != nil {
		t.Fatal(err)
	}
	if len(resp4.Msg.Items) != 1 || resp4.Msg.Items[0].Action != adminv1.SyncAction_SYNC_ACTION_NOOP || !resp4.Msg.InSync {
		t.Fatalf("post-rename apply = %+v", resp4.Msg.Items)
	}
}
