package main

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"

	"github.com/spf13/cobra"
)

// The committed CLI reference is regenerated by `go generate ./cmd/moth`
// (or `go run ./cmd/moth docs gen`); TestCLIReferenceUpToDate fails when
// it drifts from the command tree.
//
//go:generate go run . docs gen --dir ../../docs/cli

// newDocsCmd is the hidden dev helper behind the committed CLI reference:
// docs/cli/ is the content tree the milestone-09 website publishes (and
// milestone 10 embeds at /docs), and the release pipeline assembles the
// agent skill from it.
func newDocsCmd() *cobra.Command {
	cmd := &cobra.Command{
		Use:    "docs",
		Short:  "Generate the CLI documentation (dev helper)",
		Hidden: true,
	}
	cmd.AddCommand(newDocsGenCmd())
	return cmd
}

func newDocsGenCmd() *cobra.Command {
	var dir string
	cmd := &cobra.Command{
		Use:   "gen",
		Short: "Render the cobra command tree to a markdown reference",
		Args:  cobra.NoArgs,
		RunE: func(cmd *cobra.Command, _ []string) error {
			if err := os.MkdirAll(dir, 0o755); err != nil {
				return err
			}
			path := filepath.Join(dir, "reference.md")
			if err := os.WriteFile(path, renderCLIReference(cmd.Root()), 0o644); err != nil {
				return err
			}
			_, err := fmt.Fprintln(cmd.OutOrStdout(), path)
			return err
		},
	}
	cmd.Flags().StringVar(&dir, "dir", filepath.Join("docs", "cli"), "output directory")
	return cmd
}

// renderCLIReference renders every visible command to one deterministic
// markdown document: sections in cobra's sorted order, one per command,
// with usage line and local flags. Hidden commands and cobra's built-in
// help/completion are omitted.
func renderCLIReference(root *cobra.Command) []byte {
	var b strings.Builder
	b.WriteString("<!-- Generated by `moth docs gen`. Do not edit; regenerate with `go generate ./cmd/moth`. -->\n\n")
	b.WriteString("# moth CLI reference\n\n")
	b.WriteString(root.Short + "\n\n")
	b.WriteString("This tree (`docs/`) is the documentation content the milestone-09 " +
		"website publishes; the generated reference below always matches the " +
		"released binary's command surface.\n")
	for _, c := range root.Commands() {
		writeCommandSection(&b, c)
	}
	return []byte(b.String())
}

func writeCommandSection(b *strings.Builder, cmd *cobra.Command) {
	if !cmd.IsAvailableCommand() || cmd.Name() == "help" || cmd.Name() == "completion" {
		return
	}
	fmt.Fprintf(b, "\n## %s\n\n", cmd.CommandPath())
	desc := cmd.Short
	if cmd.Long != "" {
		desc = cmd.Long
	}
	b.WriteString(strings.TrimRight(desc, "\n") + "\n")
	if cmd.Runnable() {
		fmt.Fprintf(b, "\n```\n%s\n```\n", cmd.UseLine())
	}
	if flags := cmd.NonInheritedFlags(); flags.HasAvailableFlags() {
		fmt.Fprintf(b, "\nFlags:\n\n```\n%s```\n", flags.FlagUsages())
	}
	for _, c := range cmd.Commands() {
		writeCommandSection(b, c)
	}
}
